language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lmkawakami
  password:
    secure: GPOtDKWGtTDouW8VuGg3JR10EV15wetnsK7NpKQKcvqMaSnyGEyorignihkpQfSib0h+GdhQpSicgs7BdjsXR0U9+PfGBkTa9byH18huXwQsk+JkJSzr200ORvCFad1DovXmEBbxrt7a3n+NRzGs7o52MaWCDRMSlXGdytibgeGUcxUN1VAFxGOooaLQlioNj95mvYyAd3508OE+Y3Hr3/LGTvJJCJXiKo8W6gW8AQ749Dl1ooJHExv8oQ9EfEV4HCGU03FbmO5ZOQdLlOSSdRYkUZDnDl/MkMcOZ0QXI36BVVJBEKZRMrVUwmuGDeaLXx+ziWC/DPc3t4sy6TsSSbUwpGmrtzHUBM7LA86ur/w9pvNLINinHxVSdo7svyqIdUJGlyqDuTYNrMMpz5p/r7jvrHiGPd1JL1ulVTRpxDSLWY8njwPM42wO7wUVGaFVL4pbrKK/6NZTncnjw2WfZcTdaehXVyR5mQrT1zeS0H+UaPt31LOPmp+q4qiKZjFtveGFRt9i0jBXRXoFkCptZSfPL0f36CI2NC1LH4r5iLdpycYRZLPdN8ktFh3iwXY0T35x871RsTNHMamtmVyDBZN4vmR1MDNLnRdOIuXUTffdB+ZmALVxIoyqCv7dg8o95oAzpForOe+dpyLeslZrjUxIp3/kYr5mVdEsvYxX6SU=
  on:
    repo: lmkawakami/didatictests
    python: 3.8
    branches:
      only:
        - master
